name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - fleeks-team

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Please search existing issues before creating a new one to avoid duplicates.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what went wrong...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Enter '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: CLI Version
      description: What version of Fleeks CLI are you using? Run `fleeks --version`
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      options:
        - Windows 11
        - Windows 10
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Linux (Ubuntu)
        - Linux (Debian)
        - Linux (Fedora)
        - Linux (Arch)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What version of the OS are you running?
      placeholder: "e.g., Windows 11 23H2, macOS 14.1, Ubuntu 22.04"
    validations:
      required: false

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Which environment were you using?
      options:
        - Development
        - Staging
        - Production
        - Not applicable
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell
      placeholder: |
        Paste your logs here...
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: |
        You can drag and drop images here or paste them.
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Share your configuration (remove sensitive data like API keys!)
      render: yaml
      placeholder: |
        # Your ~/.fleeksconfig.yaml (sanitized)
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: |
        Any additional information that might help us understand the issue...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/fleeks-inc/fleeks-cli/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched for similar issues
          required: true
        - label: I have tested with the latest version
          required: false
        - label: I have included all relevant information
          required: true
