name: Question
description: Ask a question about Fleeks CLI
title: "[Question]: "
labels: ["question"]

body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! 🤔
        
        Please check our [documentation](https://github.com/fleeks-inc/fleeks-cli/blob/main/README.md) first.
        For general discussions, consider using [GitHub Discussions](https://github.com/fleeks-inc/fleeks-cli/discussions).

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: |
        How do I...?
        What's the best way to...?
        Can Fleeks CLI...?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation
        - Configuration
        - Commands / Usage
        - Authentication
        - Workspaces
        - Agents
        - Containers
        - Files
        - Terminal
        - Environment Management
        - API Integration
        - Troubleshooting
        - Best Practices
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Provide any relevant context, what you've tried, or related information
      placeholder: |
        I've tried...
        I'm working on...
        My setup includes...
    validations:
      required: false

  - type: textarea
    id: code
    attributes:
      label: Relevant Code or Commands
      description: If applicable, share the code or commands related to your question
      render: bash
      placeholder: |
        fleeks workspace create my-project
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/fleeks-inc/fleeks-cli/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
